# fly.toml app configuration file generated for data-ghost-backend on 2025-07-19T16:54:02-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'data-ghost-backend'
primary_region = 'iad'

[experimental]
  auto_rollback = true

# [build]
#   image = 'python:3.11-slim'

[env]
  PORT = '8080'

[[services]]
  protocol = 'tcp'
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '10s'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
